clip_denoised: true
num_samples: 128
batch_size: 8
use_ddim: false
model_path: /home/anon/artifacts/diff_celeba_all_uncond/ema_0.9999_500000.pt
classifier_paths: 
- /home/anon/artifacts/hair_fp32_cls/model149999.pt
- /home/anon/artifacts/age_fp32_cls/model149999.pt
guidance_weights: 
- [10, 10.0]
- [10.0, 10.0]
image_size: 64
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
num_head_channels: -1
attention_resolutions: 16,8
channel_mult: ''
dropout: 0.0
class_cond: false  # Used to load the diffusion model; we want the conditioning to go through the classifier only
use_checkpoint: false
use_scale_shift_norm: true
resblock_updown: false
dtype: fp16  # Diffusion in fp16
use_new_attention_order: false
learn_sigma: false
diffusion_steps: 4000
noise_schedule: linear
timestep_respacing: '250'  # instead of 4k steps; faster sampling
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_dtype: fp32
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
seed: 0
cfg_from: null
cfg_save_path: null
