seed: 0
cfg_from: null
cfg_save_path: null
train_data_lib: diff_exp.data.attribute_celeba_dataset
valid_data_lib: null
train_save_path: ./datasets/blond_black_hair_extreme_ensemble_train
valid_save_path: null

train_dataset:
  target_attr: "Black_Hair"
  data_dir: "../data"
  split: "train"
  filter_path: "../data/blond_black_hair_extreme_ensemble/train.txt"

train_transform: 
- - center_crop
  - size: 178
- - resize
  - size: 64

valid_transform: null