seed: 0
cfg_from: null
cfg_save_path: null
train_data_lib: diff_exp.data.npz_dataset
valid_data_lib: null
train_save_path: ./datasets/green_lips_train
valid_save_path: null
train_transform: 
- - image_from_array
valid_transform: null
train_dataset:
  npz_path: /raid/users/anon/samples/green_lips_train.npz


