data_dir: datasets/green_lips_train
use_wandb_logger: true
wandb_project: green_lips_classifier
val_data_dir: null
noised: true
iterations: 150000
lr: 0.0003
weight_decay: 0.0
anneal_lr: false
batch_size: 64
microbatch: -1
schedule_sampler: uniform
resume_checkpoint: ''
log_interval: 10
eval_interval: 5
save_interval: 10000
image_size: 64
classifier_dtype: fp32
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
class_weights: null
learn_sigma: true
diffusion_steps: 4000
noise_schedule: cosine
timestep_respacing: ''
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
seed: 0
cfg_from: null
cfg_save_path: null
random_crop: true
random_flip: true
