clip_denoised: true
num_samples: 10000
batch_size: 32
use_ddim: false
model_path: /home/anon/artifacts/fp16_hybrid_cos_learned_sigma_extreme_smile_5_cls/ema_0.9999_250000.pt
image_size: 64
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
num_head_channels: -1
attention_resolutions: 16,8
channel_mult: ''
dropout: 0.0
class_cond: false
use_checkpoint: false
use_scale_shift_norm: true
resblock_updown: false
dtype: fp16
use_new_attention_order: false
learn_sigma: true
diffusion_steps: 4000
noise_schedule: cosine
timestep_respacing: "250"
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
seed: 0
cfg_from: null
cfg_save_path: null