seed: 0
cfg_from: null
cfg_save_path: null
train_data_lib: diff_exp.data.attribute_celeba_dataset
valid_data_lib: null
train_save_path: ./datasets/smile_ablation_60k_128x128
valid_save_path: null

train_dataset:
  target_attr: "Smiling"
  data_dir: "../data"
  split: "train"
  filter_path: "../data/celeba_smile_train_size_ablation/60k.txt"

train_transform: 
- - center_crop
  - size: 178
- - resize
  - size: 128

valid_transform: "default"