seed: 0
cfg_from: null
cfg_save_path: null
device: cuda
batch_size: 64
max_steps: 100_000
eval_every: 100
n_eval_batch: 10
save_every: 1000
log_every: 10
gpus: 1
num_workers: 40
use_wandb: true
wandb_project: smile_classifier_agree_095
recover_path: null
train_lib: diff_exp.data.attribute_celeba_dataset
valid_lib: diff_exp.data.from_npz_with_labels
arch_lib: diff_exp.models.efficientnet
optim_lib: diff_exp.optim.sgd
train_data:
  target_attr: Smiling
  data_dir: ./data
  split: train
  filter_path: FILL #./data/filtered_agree_095_split_1/train.txt
valid_data:
  npz_path: "/home/anon/samples/manual_labeled_data/celeba_valid_smile_only_100.npz"
arch:
  size: s
  num_classes: 2
optim:
  lr: 0.1
  momentum: 0.9
  dampening: 0.0
  weight_decay: 0.0
  nesterov: false
  maximize: false

train_transforms: 
- - to_tensor
- - center_crop
  - size: 178
- - resize
  - size: 64
- - normalize
  - mean: 0.5, 0.5, 0.5
  - std: 0.5, 0.5, 0.5
- - rand_horizontal_flip
  - p: 0.5


valid_transforms:
- - to_tensor
- - normalize
  - mean: 0.5, 0.5, 0.5
  - std: 0.5, 0.5, 0.5

log_transform:
- - normalize
  - mean: -1, -1, -1
  - std: 2, 2, 2