clip_denoised: true
num_samples: 1000
batch_size: 8
use_ddim: false
model_path: /home/anon/artifacts/diff_celeba_all_uncond/ema_0.9999_500000.pt
classifier_path: /home/anon/artifacts/smile_fp32_classifier/model149999.pt
class_weights:
- 0.5
- 0.5
image_size: 64
num_channels: 128
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
num_head_channels: -1
attention_resolutions: 16,8
channel_mult: ''
dropout: 0.0
class_cond: false
use_checkpoint: false
use_scale_shift_norm: true
resblock_updown: false
dtype: fp16  # Diffusion in FP16
use_new_attention_order: false
learn_sigma: false
diffusion_steps: 4000
noise_schedule: linear
timestep_respacing: '250'
use_kl: false
predict_xstart: false
rescale_timesteps: false
rescale_learned_sigmas: false
classifier_dtype: fp32  # Classifier in FP32
classifier_width: 128
classifier_depth: 2
classifier_attention_resolutions: 32,16,8
classifier_use_scale_shift_norm: true
classifier_resblock_updown: true
classifier_pool: attention
seed: 0
cfg_from: null
cfg_save_path: null
