seed: 0
cfg_from: null
cfg_save_path: null
train_data_lib: diff_exp.data.smile_hair_2d_dataset
valid_data_lib: null
train_save_path: ./datasets/2d_smile_hair_ablation
valid_save_path: null

train_dataset:
  data_dir: "../data"
  split: "train"
  filter_path: "../data/2d_smile_hair/train.txt"

train_transform: 
- - center_crop
  - size: 178
- - resize
  - size: 64

valid_transform: "default"